In [1]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Print shape, size, and dimensions
print("Shape:", my_array.shape)
print("Size:", my_array.size)
print("Dimensions:", my_array.ndim)

Shape: (3, 4)
Size: 12
Dimensions: 2


In [2]:
my_array = [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]]

first_row = my_array[0]

print("First row:", first_row)

First row: [1, 2, 3, 4]


In [3]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = my_array[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [4]:
import numpy as np

# Define the array
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_elements = my_array[1::2, 1::2]

print("All odd-indexed elements:")
print(odd_elements)

All odd-indexed elements:
[[6 8]]


In [5]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)

Random 3x3 matrix:
[[0.95040904 0.85144431 0.41323889]
 [0.53360034 0.46336112 0.24526922]
 [0.84610116 0.78255803 0.4238013 ]]


In [6]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase dimension along a new axis (axis=2 in this case)
expanded_array = original_array[:, :, np.newaxis]

# Alternatively, you can use numpy.expand_dims
# expanded_array = np.expand_dims(original_array, axis=2)

print("Original array shape:", original_array.shape)
print("Expanded array shape:", expanded_array.shape)

Original array shape: (3, 4)
Expanded array shape: (3, 4, 1)


In [7]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array using numpy.transpose
transposed_array = np.transpose(original_array)

# Alternatively, you can use the .T attribute
# transposed_array = original_array.T

print("Original array:")
print(original_array)

print("\nTransposed array:")
print(transposed_array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
import numpy as np

# Generate a 2x3 random array with values between 0 and 1
random_array = np.random.rand(2, 3)

In [9]:
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[2, 1],
                   [7, 4]])

# Compute the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original matrix:")
print(matrix)

print("\nInverse matrix:")
print(inverse_matrix)

# Verify that the product of the matrix and its inverse is the identity matrix
identity_matrix = np.dot(matrix, inverse_matrix)
print("\nProduct of the matrix and its inverse (should be identity matrix):")
print(identity_matrix)

Original matrix:
[[2 1]
 [7 4]]

Inverse matrix:
[[ 4. -1.]
 [-7.  2.]]

Product of the matrix and its inverse (should be identity matrix):
[[1. 0.]
 [0. 1.]]


In [10]:
import numpy as np

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array to a 2D array with 2 rows and 3 columns
reshaped_array = np.reshape(original_array, (2, 3))

print("Original array:")
print(original_array)

print("\nReshaped array:")
print(reshaped_array)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]
